vse: &vse
  docker:
    - image: circleci/node:8.11.3

version: 2.1
jobs:
  test:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  build:
    <<: *vse
    steps:
      - checkout
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2.1
  build:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: main
