vse: &vse
  docker:
    - image: circleci/node:8.11.3

version: 2.1
jobs:
  deploy:
    <<: *vse
    docker:
      - image: ansible/ansible:ubuntu1604
        environment:
          ANSIBLE_HOST_KEY_CHECKING: no
    steps:
      - checkout
      - run: pip install
      - run: pip install typing
      - run: pip install ansible
      - run: sudo pip install virtualenv
      - run: sudo /usr/bin/python -m pip install boto 
      - run: ansible-playbook ./ansible/ec2_deploy.yml -e "git_branch=master,ansible_python_interpreter=/usr/bin/python3"
  build:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
