- name: Terminate old instances
  hosts: localhost
  connection: local
  tasks:
    - name: Terminate Instances
      ec2_instance_info:
        region: us-east-1
      register: ec2_info
      
    - name: terminate
      ec2:
        instance_ids: "{{item.instance_id}}"
        region: us-east-2
        state: stopped
        wait: yes
      with_items: "{{ec2_info.instances}}"
